### ISSUE TITLE
Set wamp_server and wamp_http for individual hosts

### ISSUE THREAD

**Issue by jlashner** [simonsobs/ocs#119]
The location of the wamp_server and wamp_http right now differ whether you're running your ocs script from the host (or in a docker with network_mode host) vs within a docker-container. This makes setting these values kind of confusing and makes the arguments to ocs client scripts differ depending on whether they are run in a docker (like ocs-util) vs on the host.

This can be solved by allowing `wamp_server` and `wamp_http` to be set in the default.yaml file on a per-host basis and have that override the one set in the hub section.

**Comment by BrianJKoopman** [comment]
Documented in #276. Going to link this issue to that PR as well.
