### ISSUE TITLE
Sotodlib in ocs-util

### ISSUE THREAD

**Issue by jlashner** [simonsobs/ocs#141]
It's been requested to have sotodlib installed in ocs-util dockers to do some basic timestream analysis, which I think is a good idea.

**Comment by BrianJKoopman** [comment]
Yeah, that would be good. A couple weeks ago I was using sotodlib on my machine and found I needed sotoddb. [This comment](https://github.com/simonsobs/sotoddb/issues/11#issuecomment-632146347) on a closed sotoddb issue makes me think the repo is being phased out. @mhasself is this happening soon? Or should we setup with sotoddb for now?

**Comment by BrianJKoopman** [comment]
Closed by #142.
