### ISSUE TITLE
publish_to_feed should not require user to set from_reactor

### ISSUE THREAD

**Issue by mhasself** [simonsobs/ocs#237]
Agents that have "non-blocking" operations, running in the reactor, have to pass from_reactor=True to every call.  That has caused confusion and loss of data... and we know how to do better these days.

By default, OCSAgent.publish_to_feed should use ocs.ocs_twisted.in_reactor_context to figure out if it should callFromThread or not.  The from_reactor argument can remain but should be deprecated unless someone can think of why we'd ever want to do this the wrong way.

https://github.com/simonsobs/ocs/blob/fce3eb96b4d9ed568289f886b3a451446b984e22/ocs/ocs_agent.py#L445

**Comment by BrianJKoopman** [comment]
Fixed in #241.
