### ISSUE TITLE
Create tests which verify functionality of OCS

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/ocs#28]
We would benefit from tests which verify individual parts work as expected, i.e. register this agent, did it register as expected? aggregate this data, is the data the correct shape? etc.

**Comment by mhasself** [comment]
I think we can implement something starting from the examples/miniobs.  E.g. a Docker container that sets up miniobs and then exercise it more carefully (like checking that data files have been produced and have roughly the right contents).
