### ISSUE TITLE
Aggregator writes duplicate data

### ISSUE THREAD

**Issue by mhasself** [simonsobs/ocs#365]
Likely due to implementation of `subscribe_on_start`.  Likely happens when aggregator loses connection to crossbar and then reconnects.

More discussion (private): https://github.com/simonsobs/daq-discussions/discussions/63

**Comment by BrianJKoopman** [comment]
@mhasself are you working on this? Happy to implement and test that fix from the discussion otherwise.

**Comment by mhasself** [comment]
> @mhasself are you working on this? Happy to implement and test that fix from the discussion otherwise.

No, I am not.  Great!
