### ISSUE TITLE
Is ocs-util image used by anyone?

### ISSUE THREAD

**Issue by mhasself** [simonsobs/ocs#372]
The ocs-util image is built and pushed along with ocs and ocs-crossbar.

Is this used anywhere?

It caught my eye because it installs sotoddb and sotodlib v0.3.0.  Those are pretty useless at this point.

**Comment by jlashner** [comment]
Possibly old lab servers.... but I think it should be fine if we stop updating and building dockers

**Comment by BrianJKoopman** [comment]
If it's unused then I'm in favor of dropping it.
