### ISSUE TITLE
Aggregator remains subscribed to removed provider feeds

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/ocs#74]
The OCS Aggregator remains subscribed to provider feeds, even if those providers have been removed by the registry.

If, for some reason, an Agent is unregistered (for instance, if the registry loses track of the agent heartbeat for more than 5 seconds), then the registry removes the agent from the registered agents list. The aggregator, in turn, removes it from the providers and prov_id lists. However, if the agent is still actually active and publishing data to the feed, then the aggregator still receives that data and the `_data_handler()` method is still invoked. This [method tries to reference the agent](https://github.com/simonsobs/ocs/blob/5835febc52e0ae65c3ef0f22a9bcb0f89bc9ccf1/agents/aggregator/aggregator_agent.py#L168) address and session ID as a key to the prov_id list. This raises a KeyError in the aggregator.

I think the best solution here is to have the aggregator unsubscribe from the feeds that are removed. This will require the OCSAgent class track its subscriptions in order to call `sub.unsubscribe()`. See [example from autobahn repo][1].

## Testing
This scenario can be tested with some new code introduced in https://github.com/simonsobs/ocs/pull/73, https://github.com/simonsobs/socs/pull/25, and https://github.com/simonsobs/socs/pull/26. 

Setup these containers:
* crossbar server
* registry
* aggregator
* ls240 agent
* ls240 simulator
* ocs client

You can observe the ls240 agent begin to take data, the registry register the agent, and the aggregator record the data. Then if you disable the ls240 agent heartbeat the described errors occur.

[1]: https://github.com/crossbario/autobahn-python/blob/aedf45b09058de18e1a7ae5d73ee868051e9458d/examples/twisted/wamp/pubsub/unsubscribe/frontend.py

**Comment by mhasself** [comment]
I believe this is not a concern, after #78 .
