### ISSUE TITLE
Site parser

### ISSUE THREAD

**Issue by jlashner** [simonsobs/ocs#77]
I think it would be useful if instead of having to call `site_config.reparse_args`, we created a `SiteParser` class that subclassed `argparse.ArgumentParser`, which calls `parse_args` on the combination of command line arguments and the arguments found in the site-config file. 

This would make it so that any options specified in the parser like `required` or `type` would be applied to site-config args as well. Also you wouldn't have to run `reparse_args`.

**Comment by jlashner** [comment]
Realizing this is the same problem as issue #30. But I think this would be a good solution to that.

**Comment by mhasself** [comment]
Resolved in #82
